apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgBFBvJyXqejDQ2og8m76Dl+Ysg6E6a6cjteRnK+SztIcZEK9IQ76wSOy1nsiXfeONjpcmqwOW7SrJ1OvS/bTzAL1KFXUt+UVkQAwZyX5PM5erIShKy7vn+DC3ZsDPcrHcoAv3v8eW+fyDttrrfqOZH12PVhtPbWD/oopXAluy0td8pwv67kv5y67RLn2UWUN8ugpBScEVGIg5THSGBILClGw2P1GmRNCTvE/gxdxiufdPWvGixvKHyYsn+AK5R3uKCGctkCy/K5Rwa3cc2v78BxZdleZonVZb52LgQ77DfzUsY9RDsK23C0G57SPW6/RW/DTzpUGvRI03yXjmsBIVWRFqDVFMEnMGATenh9Lf8NXq6UiSLbXLoPi29YZIywy+9r53boUyCvduEyRs87It3XIar9qEZr/L4D3ewzb2qF4o8oNW4YWMAXbu9iilQUSUtVrhTg7qgfov7AHktc+uESGGpx891gDC4J8AOJQjqsdQPldCTgZGhOIMQU/GbSBN8M27Xyfos+P/l6FWhAZLLBwVSiepejx1JSffRttu4vc1E5mtTmS15gZsqHp/OIUJvUnYNbQa4oGOdz9Q4zCQicQz6TWxL5+zBuo4TnqocWHBoSGGYa8eBq/tEb7Hf5xy6nkhFHrI7Q4xPK52hfHGZIB9hWUl5MInvph7XPu5Cjdblq2KZZ+wXHutiFKFP2R2zFfTs=
    username: AgCIhh9taUHCmajz2qeW7mg888Dg8xeSjqM8wy1FfB7GjMek3xwcnmK7J7VcIsA3QXkT9Ql/E1eJOHhqsEeV4WfYYZEW+KvgjikKVI/ss0trp+QytQebHdpeABfTxoq4os5xE9e8KPQ6JS+l/CKMW1oJxe9J3ko6A9aa9hvVM7woG0V11r32PMNyzobeuzrOfnwQ/APjsrlQila1db95G7QFRlPr15v3sCW4HvnshaLdAtU3YdQnu7M2lJ7hjIgWdytuXTeWZakfoANQSwge3ASVUTexBLaqLaJu58APqjFK85bgbFgrJHSuxWqu/yZSeH87PpvwqJ6oV7V3nZYSzI0rYsuOCi/vFSti1cb7E3FCmMg7XWiipCpTOPNX5ozUAKQFEyJ6K2njZw/kr7eSWxbs/HmwnjCXCgcf/UG02Ffpkao9cjIR7ZkFl6vgElCLpsgi+1tw8VMl8UFDKZKOYYx5PTbj1/nwdz9DN+D2qZ0X0TKnC3wTEiTetciP8Gk+jT0wmrSRWa1vSm9OBFoEMz3RzMxxdtkb8doSCvoh6uYXB2kbFyr6PZGPIBgMLyRSiWrs23cSv0j1++591d1GQnbeQbdAIW7xfkZj4m3+YJyjQn8Zd6w3r4352T/yUhdh4jYXAxsJ/MVj0uTrOUdiLBIFbpv8zyijbuIRDOVJLSWFnJ7hmb17cut1gXfpbEEkhH/33Y4=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default

